package SimpleType


const (
	PRINT_METHOD_CODE_EPL = "EPL"
	PRINT_METHOD_CODE_SPL = "SPL"
	PRINT_METHOD_CODE_ZPL = "ZPL"
	PRINT_METHOD_CODE_STARPL = "STARPL"
	PRINT_METHOD_CODE_GIF = "GIF"

	// Format
	IMG_FORMAT_CODE_GIF = "GIF"
	IMG_FORMAT_CODE_PNG = "PNG"

	INSTRUCTION_CODE_EXCHANGE_LIKE_ITEM_ONLY = "01"
	INSTRUCTION_CODE_EXCHANGE_DRIVER_INSTRUCTIONS_INSIDE = "02"

	// language
	CHARACTER_SET_DANISH = "dan"
	CHARACTER_SET_DUTCH = "nld"
	CHARACTER_SET_FINNISH = "fin"
	CHARACTER_SET_FRENCH = "fra"
	CHARACTER_SET_GERMAN = "deu"
	CHARACTER_SET_ITALIAN = "itl"
	CHARACTER_SET_NORWEGIAN = "nor"
	CHARACTER_SET_POLISH = "pol"
	CHARACTER_SET_PORUGUESE = "por"
	CHARACTER_SET_SPANISH = "spa"
	CHARACTER_SET_SWEDISH = "swe"
	CHARACTER_SET_CZECH = "ces"
	CHARACTER_SET_HUNGARIAN = "hun"
	CHARACTER_SET_SLOVAK = "slk"
	CHARACTER_SET_RUSSIAN = "rus"
	CHARACTER_SET_TURKISH = "tur"
	CHARACTER_SET_ROMANIAN = "ron"
	CHARACTER_SET_BULGARIAN = "bul"
	CHARACTER_SET_ESTONIAN = "est"
	CHARACTER_SET_GREEK = "ell"
	RACTER_SET_LATVIAN = "lav"
)